# GENERATED by tools/build.py mission from src/robot.py - do not edit, edit robot.py
from vex import *
PORT_Z = Ports.PORT1
PORT_HOME = Ports.PORT2
PORT_TOUCH = Ports.PORT3
PORT_X = Ports.PORT5
PORT_OPTICAL = Ports.PORT7
PORT_DISTANCE = Ports.PORT8
PORT_GRIP = Ports.PORT9
HUE_RANGES = {'red': (330.0, 25.0), 'green': (70.0, 170.0), 'blue': (180.0, 270.0)}
brain = Brain()

class MotionError(Exception):
    pass

class Hardware:

    def __init__(self):
        self.home = Bumper(PORT_HOME)
        self.touch = Touchled(PORT_TOUCH)
        self.has_touch = self.touch.installed()
        self.distance = Distance(PORT_DISTANCE)
        self.optical = Optical(PORT_OPTICAL)
        self.mx = Motor(PORT_X, True) if False else Motor(PORT_X)
        self.mz = Motor(PORT_Z, True) if False else Motor(PORT_Z)
        self.mg = Motor(PORT_GRIP)

    def missing(self):
        devices = (('home switch', self.home), ('distance', self.distance), ('optical', self.optical), ('X', self.mx), ('Z', self.mz), ('grip', self.mg))
        return [name for name, dev in devices if not dev.installed()]

    def stop_all(self):
        for m in (self.mx, self.mz, self.mg):
            m.stop()

def now_ms():
    return brain.timer.time(MSEC)

def median(values):
    return sorted(values)[len(values) // 2]

def distance_mm(hw):
    d = hw.distance.object_distance(MM)
    return d if 0 < d <= 1000.0 else None

def distance_median(hw, n):
    values = []
    for _ in range(n):
        d = distance_mm(hw)
        if d is not None:
            values.append(d)
        wait(15, MSEC)
    return median(values) if len(values) > n // 2 else None

def hue_median(hues):
    if max(hues) - min(hues) > 180:
        hues = [h + 360 if h < 180 else h for h in hues]
    return median(hues) % 360

def classify_hue(h):
    if h is not None:
        for colour in ('red', 'green', 'blue'):
            lo, hi = HUE_RANGES[colour]
            if lo <= h <= hi if lo <= hi else h >= lo or h <= hi:
                return colour
    return 'unknown'

def buttons(hw):
    return (brain.buttonLeft.pressing(), brain.buttonRight.pressing(), brain.buttonCheck.pressing(), hw.has_touch and hw.touch.pressing())

def wait_press(hw):
    while True:
        l, r, c, t = buttons(hw)
        if l or r or c or t:
            while True in buttons(hw):
                wait(20, MSEC)
            return 'L' if l else 'R' if r else 'C' if c else 'T'
        wait(20, MSEC)

def say(*lines):
    brain.screen.clear_screen()
    for i, line in enumerate(lines):
        brain.screen.set_cursor(i + 1, 1)
        brain.screen.print(line)
    print('E,' + ' | '.join(lines))
_t_live = [0]

def live(r, d, period=200):
    if now_ms() - _t_live[0] < period:
        return
    _t_live[0] = now_ms()
    x, z = (r.X.mm(), r.Z.mm())
    if d is None:
        print('R,%.1f,%.1f,-1' % (x, z))
    else:
        print('R,%.1f,%.1f,%.1f,%.1f,%.1f' % (x, z, d, x + 0.0, z + d - 10.0))

class Axis:

    def __init__(self, name, motor, scale, lo, hi):
        self.name, self.m, self.k = (name, motor, scale)
        self.lo, self.hi = (lo, hi)
        self.target = 0.0
        self.t_start = 0
        self.timeout = 0
        motor.set_stopping(HOLD)
        motor.set_position(0, DEGREES)

    def deg(self):
        return self.m.position(DEGREES)

    def mm(self):
        return self.deg() * self.k

    def expected_ms(self, distance, speed):
        mm_s = self.k * 720.0 * speed / 100.0
        return 2.0 * abs(distance) * 1000.0 / mm_s + 1500

    def start_move(self, target, speed):
        if not self.lo <= target <= self.hi:
            raise MotionError('%s target outside travel: %.1f' % (self.name, target))
        self.target = target
        self.t_start = now_ms()
        self.timeout = self.expected_ms(target - self.mm(), speed)
        self.m.set_timeout(self.timeout + 500, MSEC)
        self.m.spin_to_position(target / self.k, DEGREES, speed, PERCENT, False)

    def arrived(self):
        return abs(self.mm() - self.target) <= 1.0

    def check(self):
        if now_ms() - self.t_start > self.timeout:
            raise MotionError(self.name + ' motion timed out')
        if now_ms() - self.t_start > 150 and self.m.is_done() and (not self.arrived()):
            raise MotionError(self.name + ' motion blocked')

    def move_to(self, target, speed):
        self.start_move(target, speed)
        try:
            while not self.arrived():
                self.check()
                wait(15, MSEC)
        finally:
            self.halt()

    def jog(self, speed):
        self.m.spin(FORWARD, speed, PERCENT)

    def halt(self):
        self.m.stop()

class Gripper:

    def __init__(self, motor):
        self.m = motor
        motor.set_stopping(HOLD)
        motor.set_position(0, DEGREES)

    def move(self, degrees, speed):
        self.m.set_timeout(5000, MSEC)
        self.m.spin_to_position(degrees, DEGREES, speed, PERCENT, True)
        if abs(self.deg() - degrees) > 30:
            raise MotionError('gripper did not reach %.0f degrees' % degrees)

    def open(self):
        self.move(-500, 20)

    def close(self):
        self.move(0, 50)

    def deg(self):
        return self.m.position(DEGREES)

    def jog(self, speed):
        self.m.spin(FORWARD, speed, PERCENT)

    def halt(self):
        self.m.stop()

class Robot:

    def __init__(self):
        self.hw = Hardware()
        self.X = Axis('X', self.hw.mx, 0.1, -1200.0, 0.0)
        self.Z = Axis('Z', self.hw.mz, 0.1, 0.0, 400.0)
        self.grip = Gripper(self.hw.mg)
        self.homed = False

    def stop_all(self):
        self.hw.stop_all()

    def home_x(self):
        if self.Z.mm() > 2.0:
            raise MotionError('retract Z before homing')
        if not self.hw.home.installed():
            raise MotionError('home switch missing')
        self.homed = False
        say('HOME', 'moving right to switch')
        t0, x0 = (now_ms(), self.X.mm())
        try:
            while self.hw.home.pressing():
                if now_ms() - t0 > 5000 or abs(self.X.mm() - x0) > 25.0:
                    raise MotionError('home switch stuck pressed')
                self.X.jog(-20)
                wait(15, MSEC)
            self.X.halt()
            t0, x0 = (now_ms(), self.X.mm())
            last_motion, last_x = (t0, x0)
            while True:
                if now_ms() - t0 > 120000 or self.X.mm() - x0 > 1225.0:
                    raise MotionError('home switch not reached')
                if self.hw.home.pressing():
                    self.X.halt()
                    wait(60, MSEC)
                    if self.hw.home.pressing():
                        break
                if abs(self.X.mm() - last_x) >= 0.5:
                    last_motion, last_x = (now_ms(), self.X.mm())
                elif now_ms() - last_motion > 1500:
                    raise MotionError('X stalled before home switch')
                self.X.jog(20)
                wait(15, MSEC)
            self.X.m.set_position(0, DEGREES)
            self.X.move_to(-10.0, 20)
            if self.hw.home.pressing():
                raise MotionError('home switch did not release')
            self.homed = True
            say('HOME set', 'X=0 at right switch')
        finally:
            self.X.halt()

    def move_x(self, target, speed, carrying=False):
        if not self.homed or self.Z.mm() > 2.0:
            raise MotionError('X needs home and retracted Z')
        self.X.start_move(target, speed)
        lost = 0
        try:
            while not self.X.arrived():
                self.X.check()
                if target > self.X.mm() and self.hw.home.pressing():
                    raise MotionError('unexpected home switch during travel')
                d = distance_mm(self.hw)
                if carrying:
                    lost = lost + 1 if d is None or d > 20.0 else 0
                    if lost >= 3:
                        raise MotionError('cube lost during transport')
                live(self, d)
                wait(15, MSEC)
        finally:
            self.X.halt()

class CubeSearch:

    def __init__(self):
        self.samples = []

    def add(self, x, z):
        if self.samples:
            step = self.samples[-1][0] - x
            if step < 1.0:
                return None
            if step > 2.0:
                self.samples = []
        self.samples.append((x, z))
        span = 132.0
        while self.samples[0][0] - x > span:
            self.samples.pop(0)
        return self.target()

    def clear_side(self, index, step, edge, depth):
        while 0 <= index < len(self.samples):
            x, z = self.samples[index]
            if z is None or z < depth:
                return False
            if abs(x - edge) >= 17.0:
                return True
            index += step
        return False

    def target(self):
        s = self.samples
        i = 0
        while i < len(s):
            z = s[i][1]
            if z is None or z < 0 or z >= 312.5:
                i += 1
                continue
            first = i
            near = far = z
            i += 1
            while i < len(s) and s[i][1] is not None:
                z = s[i][1]
                if abs(z - s[i - 1][1]) > 20.0:
                    break
                near, far = (min(near, z), max(far, z))
                i += 1
            if first == 0 or i == len(s):
                continue
            right = (s[first - 1][0] + s[first][0]) / 2
            left = (s[i - 1][0] + s[i][0]) / 2
            width = right - left
            if not 72.0 <= width <= 90.0:
                continue
            if far - near > 90.0:
                continue
            centre = (left + right) / 2
            beam_x = centre + 0.0
            if not left <= beam_x <= right:
                continue
            best = first
            for j in range(first + 1, i):
                if abs(s[j][0] - beam_x) < abs(s[best][0] - beam_x):
                    best = j
            grab_z = s[best][1]
            depth = max(grab_z + 80.0, far) + 5.0
            if self.clear_side(first - 1, -1, right, depth) and self.clear_side(i, 1, left, depth):
                return (centre, grab_z)
        return None

def find_cube(r, failed, deadline):
    r.move_x(-350.0, 80)
    wait(500, MSEC)
    search = CubeSearch()
    r.X.start_move(-1150.0, 25)
    last_x, last_t = (r.X.mm(), now_ms())
    velocity = 0.0
    try:
        while not r.X.arrived() and now_ms() < deadline:
            r.X.check()
            x, t = (r.X.mm(), now_ms())
            if t > last_t:
                velocity = 0.7 * velocity + 0.3 * (x - last_x) * 1000.0 / (t - last_t)
            last_x, last_t = (x, t)
            d = distance_mm(r.hw)
            z = None if d is None else r.Z.mm() + d - 10.0
            target = search.add(x - velocity * 0.0 + 0.0, z)
            live(r, d)
            if target is not None and (not any((abs(target[0] - old) < 37.5 for old in failed))):
                if -1200.0 <= target[0] <= 0 and target[1] <= 400.0:
                    return target
            wait(15, MSEC)
    finally:
        r.X.halt()
    return None

def pick_cube(r, target):
    x, z = target
    r.move_x(x, 25)
    r.grip.open()
    r.Z.move_to(max(0.0, z - 30.0), 80)
    r.Z.start_move(min(z + 20.0, 400.0), 20)
    reached = False
    try:
        while True:
            d = distance_mm(r.hw)
            live(r, d)
            if d is not None and d <= 10.0:
                reached = True
                break
            if r.Z.arrived():
                break
            r.Z.check()
            wait(15, MSEC)
    finally:
        r.Z.halt()
    if reached:
        r.grip.close()
    r.Z.move_to(0.0, 50)
    d = distance_median(r.hw, 5)
    if reached and d is None:
        raise MotionError('cannot confirm whether cube is held')
    return reached and d is not None and (d <= 20.0)

def identify(r):
    for _ in range(2):
        hues = []
        for _ in range(7):
            if r.hw.optical.is_near_object() or r.hw.optical.brightness() >= 5.0:
                hues.append(r.hw.optical.hue())
            wait(15, MSEC)
        colour = classify_hue(hue_median(hues)) if len(hues) > 3 else 'unknown'
        if colour != 'unknown':
            return colour
    return 'unknown'

def place_cube(r, slot):
    x, z = slot
    r.move_x(x, 50, carrying=True)
    r.Z.move_to(z, 50)
    r.grip.open()
    r.Z.move_to(0.0, 80)
    d = distance_median(r.hw, 5)
    if d is not None and d <= 20.0:
        raise MotionError('cube still held after release')
    r.grip.close()

class Mission:

    def __init__(self, robot):
        self.r = robot

    def run(self):
        r = self.r
        slots = {'green': ((-250.0, 240.0), (-250.0, 150.0), (-250.0, 60.0)), 'red': ((-140.0, 240.0), (-140.0, 150.0), (-140.0, 60.0)), 'blue': ((-50.0, 240.0), (-50.0, 150.0), (-50.0, 60.0))}
        used = {'green': 0, 'red': 0, 'blue': 0}
        failed = []
        deadline = now_ms() + 600000
        r.home_x()
        reason = 'time reserved for return'
        while now_ms() < deadline - 90000:
            say('SEARCH', 'moving left')
            target = find_cube(r, failed, deadline - 90000)
            if target is None:
                reason = 'no accessible cube or search time finished'
                break
            say('PICK', 'X %.1f Z %.1f' % target)
            if not pick_cube(r, target):
                failed.append(target[0])
                say('PICK missed', 'skipping this position')
                if len(failed) >= 3:
                    reason = 'pick failure limit'
                    break
                continue
            colour = identify(r)
            print('C,%.1f,%.1f,%s' % (target[0], target[1], colour))
            if colour == 'unknown' or used[colour] >= len(slots[colour]):
                r.move_x(-10.0, 50, carrying=True)
                say('STOP: cube held', 'unknown colour or zone full')
                return
            say('RETURN / SORT', colour)
            place_cube(r, slots[colour][used[colour]])
            used[colour] += 1
            print('E,placed %s (%d)' % (colour, used[colour]))
        r.move_x(-10.0, 80)
        say('DONE', reason, 'G%d R%d B%d' % (used['green'], used['red'], used['blue']))

def startup(r):
    missing = r.hw.missing()
    if missing:
        say('MISSING', ', '.join(missing))
        return False
    if True:
        say('CALIBRATE FIRST', 'see docs/calibration.md')
        return False
    if not -1200.0 < -1150.0 < -350.0 < -10.0 < 0:
        raise MotionError('check X home/search limits')
    if 0.1 <= 0 or 0.1 <= 0 or 15.0 < 15:
        raise MotionError('check scales and side clearance')
    for slots in (((-250.0, 240.0), (-250.0, 150.0), (-250.0, 60.0)), ((-140.0, 240.0), (-140.0, 150.0), (-140.0, 60.0)), ((-50.0, 240.0), (-50.0, 150.0), (-50.0, 60.0))):
        for x, z in slots:
            if not -350.0 < x < -10.0 or not 0 < z <= 400.0:
                raise MotionError('check sorting slot positions')
    r.hw.optical.set_light(100)
    say('READY', 'arm in, gripper closed', 'Check or LED = start')
    return True

def select_mode(r):
    return 'MISSION'

def main():
    r = Robot()
    try:
        mode = select_mode(r)
        print('E,mode ' + mode)
        if not startup(r):
            return
        while wait_press(r.hw) not in ('C', 'T'):
            pass
        Mission(r).run()
    except MotionError as e:
        say('STOP', str(e))
    finally:
        r.stop_all()
if __name__ == '__main__':
    main()
