# GENERATED by tools/build.py cal-rate from src/robot.py - do not edit, edit robot.py
from vex import *
PORT_Z = Ports.PORT1
PORT_BUMPER = Ports.PORT2
PORT_TOUCH = Ports.PORT3
PORT_X = Ports.PORT5
PORT_OPTICAL = Ports.PORT7
PORT_DISTANCE = Ports.PORT8
PORT_GRIP = Ports.PORT9
brain = Brain()

class MotionError(Exception):
    pass

class Hardware:

    def __init__(self):
        self.touch = Touchled(PORT_TOUCH)
        self.optical = Optical(PORT_OPTICAL)
        self.distance = Distance(PORT_DISTANCE)
        self.bumper = Bumper(PORT_BUMPER)
        self.mx = Motor(PORT_X, True) if False else Motor(PORT_X)
        self.mz = Motor(PORT_Z, True) if False else Motor(PORT_Z)
        self.mg = Motor(PORT_GRIP)
        self.has_touch = self.touch.installed()

    def stop_all(self):
        for m in (self.mx, self.mz, self.mg):
            m.stop()

def now_ms():
    return brain.timer.time(MSEC)

def distance_mm(hw):
    d = hw.distance.object_distance(MM)
    if d <= 0 or d > 1000.0:
        return None
    return d

def buttons(hw):
    return (brain.buttonLeft.pressing(), brain.buttonRight.pressing(), brain.buttonCheck.pressing(), hw.has_touch and hw.touch.pressing())

def wait_press(hw):
    while True:
        l, r, c, t = buttons(hw)
        if l or r or c or t:
            while True in buttons(hw):
                wait(20, MSEC)
            return 'L' if l else 'R' if r else 'C' if c else 'T'
        wait(20, MSEC)

def say(*lines):
    brain.screen.clear_screen()
    for i, line in enumerate(lines):
        brain.screen.set_cursor(i + 1, 1)
        brain.screen.print(line)
    print('# ' + ' | '.join(lines))

class Axis:

    def __init__(self, name, motor, mm_per_deg, lo, hi):
        self.name = name
        self.m = motor
        self.k = mm_per_deg
        self.lo = lo
        self.hi = hi
        self.timeout = 0
        self.target = 0.0
        self.t_start = 0
        motor.set_stopping(HOLD)
        motor.set_position(0, DEGREES)

    def expected_ms(self, dist_mm, speed):
        mm_per_s = abs(self.k) * 720.0 * speed / 100.0
        return 2000.0 * abs(dist_mm) / mm_per_s + 1500

    def deg(self):
        return self.m.position(DEGREES)

    def mm(self):
        return self.deg() * self.k

    def start_move(self, mm, speed):
        self.target = min(max(mm, self.lo), self.hi)
        self.t_start = now_ms()
        self.timeout = self.expected_ms(self.target - self.mm(), speed)
        self.m.set_timeout(self.timeout + 500, MSEC)
        self.m.spin_to_position(self.target / self.k, DEGREES, speed, PERCENT, False)

    def arrived(self):
        return abs(self.mm() - self.target) <= 3.0

    def check(self):
        elapsed = now_ms() - self.t_start
        if elapsed > self.timeout:
            self.halt()
            raise MotionError('%s timeout at %.0f mm (target %.0f)' % (self.name, self.mm(), self.target))
        if elapsed > 150 and self.m.is_done() and (not self.arrived()):
            self.halt()
            raise MotionError('%s blocked at %.0f mm (target %.0f)' % (self.name, self.mm(), self.target))

    def halt(self):
        self.m.stop()

class Gripper:

    def __init__(self, motor):
        self.name = 'G'
        self.m = motor
        motor.set_stopping(HOLD)
        motor.set_position(0, DEGREES)

    def halt(self):
        self.m.stop()

    def deg(self):
        return self.m.position(DEGREES)

class Robot:

    def __init__(self):
        self.hw = Hardware()
        self.X = Axis('X', self.hw.mx, 0.1, 0.0, 1200.0)
        self.Z = Axis('Z', self.hw.mz, 0.1, 0.0, 400.0)
        self.grip = Gripper(self.hw.mg)

    def stop_all(self):
        self.hw.stop_all()

def median_interval(ts):
    d = sorted([ts[k + 1] - ts[k] for k in range(len(ts) - 1)])
    return d[len(d) // 2] if d else 0

def cal_rates(r):
    hw = r.hw
    say('RATES', 'arm in, X clear', 'for %.0f mm' % 300.0, 'Check = start')
    wait_press(hw)
    n = 200
    cost = []
    for name, f in (('distance', lambda: hw.distance.object_distance(MM)), ('hue', hw.optical.hue), ('encoder', lambda: hw.mx.position(DEGREES)), ('scan loop', lambda: (r.X.mm(), distance_mm(hw), hw.bumper.pressing()))):
        t0 = now_ms()
        for _ in range(n):
            f()
        cost.append((now_ms() - t0) / n)
        print('# RATE call %s: %.2f ms' % (name, cost[-1]))
    last = [None, None, None]
    times = [[], [], []]
    x0 = r.X.mm()
    t1 = t2 = 0
    for x_to in (x0 + 300.0, x0):
        r.X.start_move(x_to, 40)
        while not r.X.arrived():
            r.X.check()
            t = now_ms()
            x = r.X.mm()
            if x_to > x0:
                if not t1 and x >= x0 + 75.0:
                    t1 = t
                if not t2 and x >= x0 + 225.0:
                    t2 = t
            vals = (hw.distance.object_distance(MM), (hw.optical.hue(), hw.optical.brightness()), hw.mx.position(DEGREES))
            for i in range(3):
                if vals[i] != last[i]:
                    last[i] = vals[i]
                    if len(times[i]) < 400:
                        times[i].append(t)
            wait(2, MSEC)
    td, to, tx = [median_interval(ts) for ts in times]
    for name, ts, p in (('distance', times[0], td), ('optical', times[1], to), ('encoder', times[2], tx)):
        print('# RATE %s: %d changes, updates every %.0f ms' % (name, len(ts), p))
    if td <= 0 or t2 <= t1:
        say('RATES', 'no data:', 'nothing changed', 'or X did not move')
        wait_press(hw)
        return
    v = 150000.0 / (t2 - t1)
    loop = max(2, int(td / 2))
    err_per_v = (td + tx + loop + cost[3]) / 2000.0
    v_max = min(1.0 / err_per_v, 5000.0 / td)
    pct = min(100, int(40 * v_max / v))
    print('# now: %d%% = %.0f mm/s, edge error +-%.1f mm' % (40, v, v * err_per_v))
    print('SPEED_X_SCAN = %d    # cal_rates: %.0f mm/s, edge error +-%.1f mm' % (pct, v_max, 1.0))
    print('LOOP_MS = %d    # cal_rates: distance updates every %.0f ms' % (loop, td))
    print('# colour: optical updates every %.0f ms, %d samples need >= %.0f ms to be independent' % (to, 7, 7 * to))
    say('RATES dist %.0f ms' % td, 'opt %.0f enc %.0f ms' % (to, tx), 'scan %d%% %.0f mm/s' % (pct, v_max), 'LOOP_MS %d' % loop)
    wait_press(hw)
CAL_ROUTINES = (('Rates', cal_rates),)

def calibration_menu(r):
    r.hw.optical.set_light(100)
    i = 0
    while True:
        say('CALIBRATE', '< %s >' % CAL_ROUTINES[i][0], 'L/R choose', 'Check run')
        b = wait_press(r.hw)
        if b == 'L':
            i = (i - 1) % len(CAL_ROUTINES)
        elif b == 'R':
            i = (i + 1) % len(CAL_ROUTINES)
        elif b == 'C':
            try:
                CAL_ROUTINES[i][1](r)
            except MotionError as e:
                r.stop_all()
                say('MOTION ERROR', str(e))
                wait_press(r.hw)

def select_mode(r):
    return 'CALIBRATE'

def main():
    r = Robot()
    try:
        try:
            import gc
            gc.collect()
            print('E,heap free %d used %d' % (gc.mem_free(), gc.mem_alloc()))
        except Exception:
            pass
        mode = select_mode(r)
        print('E,mode ' + mode)
        calibration_menu(r)
    finally:
        r.stop_all()
if __name__ == '__main__':
    main()
