# GENERATED by tools/build.py cal-z from src/robot.py - do not edit, edit robot.py
from vex import *
PORT_Z = Ports.PORT1
PORT_BUMPER = Ports.PORT2
PORT_TOUCH = Ports.PORT3
PORT_X = Ports.PORT5
PORT_OPTICAL = Ports.PORT7
PORT_DISTANCE = Ports.PORT8
PORT_GRIP = Ports.PORT9
brain = Brain()

class MotionError(Exception):
    pass

class Hardware:

    def __init__(self):
        self.touch = Touchled(PORT_TOUCH)
        self.optical = Optical(PORT_OPTICAL)
        self.distance = Distance(PORT_DISTANCE)
        self.bumper = Bumper(PORT_BUMPER)
        self.mx = Motor(PORT_X, True) if False else Motor(PORT_X)
        self.mz = Motor(PORT_Z, True) if False else Motor(PORT_Z)
        self.mg = Motor(PORT_GRIP)
        self.has_touch = self.touch.installed()

    def stop_all(self):
        for m in (self.mx, self.mz, self.mg):
            m.stop()

def now_ms():
    return brain.timer.time(MSEC)

def median(values):
    s = sorted(values)
    return s[len(s) // 2]

def distance_mm(hw):
    d = hw.distance.object_distance(MM)
    if d <= 0 or d > 1000.0:
        return None
    return d

def distance_median(hw, n):
    vals = []
    for _ in range(n):
        d = distance_mm(hw)
        if d is not None:
            vals.append(d)
        wait(15, MSEC)
    if len(vals) < n // 2 + 1:
        return None
    return median(vals)

def buttons(hw):
    return (brain.buttonLeft.pressing(), brain.buttonRight.pressing(), brain.buttonCheck.pressing(), hw.has_touch and hw.touch.pressing())

def wait_press(hw):
    while True:
        l, r, c, t = buttons(hw)
        if l or r or c or t:
            while True in buttons(hw):
                wait(20, MSEC)
            return 'L' if l else 'R' if r else 'C' if c else 'T'
        wait(20, MSEC)

def say(*lines):
    brain.screen.clear_screen()
    for i, line in enumerate(lines):
        brain.screen.set_cursor(i + 1, 1)
        brain.screen.print(line)
    print('# ' + ' | '.join(lines))

class Axis:

    def __init__(self, name, motor, mm_per_deg, lo, hi):
        self.name = name
        self.m = motor
        self.k = mm_per_deg
        self.lo = lo
        self.hi = hi
        self.timeout = 0
        self.target = 0.0
        self.t_start = 0
        motor.set_stopping(HOLD)
        motor.set_position(0, DEGREES)

    def expected_ms(self, dist_mm, speed):
        mm_per_s = abs(self.k) * 720.0 * speed / 100.0
        return 2000.0 * abs(dist_mm) / mm_per_s + 1500

    def deg(self):
        return self.m.position(DEGREES)

    def mm(self):
        return self.deg() * self.k

    def jog(self, speed):
        self.m.spin(FORWARD, speed, PERCENT)

    def halt(self):
        self.m.stop()

class Gripper:

    def __init__(self, motor):
        self.name = 'G'
        self.m = motor
        motor.set_stopping(HOLD)
        motor.set_position(0, DEGREES)

    def jog(self, speed):
        self.m.spin(FORWARD, speed, PERCENT)

    def halt(self):
        self.m.stop()

    def deg(self):
        return self.m.position(DEGREES)

class Robot:

    def __init__(self):
        self.hw = Hardware()
        self.X = Axis('X', self.hw.mx, 0.1, 0.0, 1200.0)
        self.Z = Axis('Z', self.hw.mz, 0.1, 0.0, 400.0)
        self.grip = Gripper(self.hw.mg)

    def stop_all(self):
        self.hw.stop_all()
_t_live = [0]

def live(r, d, period=200):
    t = now_ms()
    if t - _t_live[0] < period:
        return
    _t_live[0] = t
    x = r.X.mm()
    z = r.Z.mm()
    if d is None:
        print('R,%.0f,%.0f,-1' % (x, z))
    else:
        print('R,%.0f,%.0f,%.0f,%.0f,%.0f' % (x, z, d, x + 0.0, z + d - 10.0))

def cal_move_deg(r, axis, deg, speed):
    axis.m.set_timeout(axis.expected_ms((deg - axis.deg()) * axis.k, speed), MSEC)
    axis.m.spin_to_position(deg, DEGREES, speed, PERCENT, False)
    wait(50, MSEC)
    while not axis.m.is_done():
        live(r, distance_mm(r.hw), 100)
        wait(15, MSEC)

def fit_line(pts):
    n = float(len(pts))
    mx = sum((p[0] for p in pts)) / n
    my = sum((p[1] for p in pts)) / n
    sxx = sum(((p[0] - mx) ** 2 for p in pts))
    sxy = sum(((p[0] - mx) * (p[1] - my) for p in pts))
    b = sxy / sxx
    a = my - b * mx
    rms = (sum(((p[1] - a - b * p[0]) ** 2 for p in pts)) / n) ** 0.5
    return (a, b, rms)

def extend_until_near(r):
    r.Z.jog(20)
    t0 = now_ms()
    t_still = None
    while now_ms() - t0 < 30000:
        d = distance_mm(r.hw)
        live(r, d, 100)
        if d is not None and d < 60.0:
            break
        if abs(r.hw.mz.velocity(PERCENT)) < 2 and now_ms() - t0 > 500:
            t_still = t_still or now_ms()
            if now_ms() - t_still > 300:
                break
        else:
            t_still = None
        wait(15, MSEC)
    r.Z.halt()
    return r.Z.deg()

def cal_z_scale(r):
    say('Z SCALE', 'Flat board across the', 'arm path, in front.', 'Check = start (auto)')
    wait_press(r.hw)
    deg_max = extend_until_near(r)
    if deg_max < 100:
        say('Z SCALE FAILED', 'arm did not extend:', 'check Z_MOTOR_REVERSED')
        print('# Z did not extend (%.0f deg): Z_MOTOR_REVERSED wrong or arm blocked' % deg_max)
        return
    pts = []
    for i in range(9):
        deg = deg_max * (8 - i) / 8
        cal_move_deg(r, r.Z, deg, 20)
        wait(300, MSEC)
        d = distance_median(r.hw, 15)
        live(r, d, 0)
        print('CAL Z deg=%.0f d=%s' % (r.Z.deg(), d))
        if d is not None:
            pts.append((r.Z.deg(), d))
    if len(pts) < 3:
        say('Z SCALE FAILED', 'board not seen')
        return
    a, b, rms = fit_line(pts)
    k = -b
    print('Z_MM_PER_DEG = %.5f    # cal_z_scale, rms %.2f mm, %d pts' % (k, rms, len(pts)))
    print('# reached Z = %.0f mm (board close or end of travel)' % (deg_max * k))
    if k < 0:
        print('# negative: flip Z_MOTOR_REVERSED')
    say('Z_MM_PER_DEG', '%.5f' % k, 'rms %.2f mm' % rms, 'copy from console')
    wait_press(r.hw)
CAL_ROUTINES = (('Z scale', cal_z_scale),)

def calibration_menu(r):
    r.hw.optical.set_light(100)
    i = 0
    while True:
        say('CALIBRATE', '< %s >' % CAL_ROUTINES[i][0], 'L/R choose', 'Check run')
        b = wait_press(r.hw)
        if b == 'L':
            i = (i - 1) % len(CAL_ROUTINES)
        elif b == 'R':
            i = (i + 1) % len(CAL_ROUTINES)
        elif b == 'C':
            try:
                CAL_ROUTINES[i][1](r)
            except MotionError as e:
                r.stop_all()
                say('MOTION ERROR', str(e))
                wait_press(r.hw)

def select_mode(r):
    return 'CALIBRATE'

def main():
    r = Robot()
    try:
        try:
            import gc
            gc.collect()
            print('E,heap free %d used %d' % (gc.mem_free(), gc.mem_alloc()))
        except Exception:
            pass
        mode = select_mode(r)
        print('E,mode ' + mode)
        calibration_menu(r)
    finally:
        r.stop_all()
if __name__ == '__main__':
    main()
